/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumCommentsInfo: (typeof import('./../components/AlbumCommentsInfo/AlbumCommentsInfo.vue'))['default']
    BarrageCommentItem: (typeof import('./../components/BarrageCommentItem/BarrageCommentItem.vue'))['default']
    BarrageComments: (typeof import('./../components/BarrrageComments/BarrageComments.vue'))['default']
    BottomBar: (typeof import('./../components/BottomBar/BottomBar.vue'))['default']
    Carousel: (typeof import('./../components/Carousel/Carousel.vue'))['default']
    CatItem: (typeof import('./../components/CatItem/CatItem.vue'))['default']
    CatsList: (typeof import('./../components/CatsList/CatsList.vue'))['default']
    CjxCustomNav: (typeof import('./../components/CjxCustomNav/CjxCustomNav.vue'))['default']
    CjxImgGrid: (typeof import('./../components/CjxImgGrid/CjxImgGrid.vue'))['default']
    CjxModal: (typeof import('./../components/CjxModal/CjxModal.vue'))['default']
    CjxSelect: (typeof import('./../components/CjxSelect/CjxSelect.vue'))['default']
    CjxSwipper: (typeof import('./../components/CjxSwipper/CjxSwipper.vue'))['default']
    CjxTabs: (typeof import('./../components/CjxTabs/CjxTabs.vue'))['default']
    CommentItem: (typeof import('./../components/CommentItem/CommentItem.vue'))['default']
    DeleteAlbum: (typeof import('./../components/DeleteAlbum/DeleteAlbum.vue'))['default']
    LikesAndCommentsCount: (typeof import('./../components/LikesAndCommentsCount/LikesAndCommentsCount.vue'))['default']
    LocationAlbum: (typeof import('./../components/LocationAlbum/LocationAlbum.vue'))['default']
    PhotoDescriptions: (typeof import('./../components/PhotoDescriptions/PhotoDescriptions.vue'))['default']
    TeamBoard: (typeof import('./../components/TeamBoard/TeamBoard.vue'))['default']
    TeamChoosing: (typeof import('./../components/TeamChoosing/TeamChoosing.vue'))['default']
    TeamTools: (typeof import('./../components/TeamTools/TeamTools.vue'))['default']
    ToolBar: (typeof import('./../components/ToolBar/ToolBar.vue'))['default']
    Tools: (typeof import('./../components/Tools/Tools.vue'))['default']
    TopBar: (typeof import('./../components/TopBar/TopBar.vue'))['default']
    TopReturning: (typeof import('./../components/TopReturning/TopReturning.vue'))['default']
  }
}
